version: '3.6'
services:
  localstack:
    image: localstack/localstack
    environment:
      SERVICES: dynamodb
      DEBUG: 1
      DEFAULT_REGION: eu-west-1
    ports:
      - "4567-4584:4567-4584"
      - "8084:8080"
